# Generated by Django 4.0.2 on 2022-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uin',
            field=models.CharField(max_length=12),
        ),
    ]
